name: Build and Deploy to Fargate

on:
  pull_request:
    types: [synchronize]

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push_api:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'synchronize' }}
    uses: ./.github/workflows/api_deployment.yml
  build_and_push_client:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'synchronize' }}
    uses: ./.github/workflows/client_deployment.yml
