name: Build and Deploy to Fargate

on:
  push:
    branches:
    - master

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push_server:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/api_deployment.yml
  build_and_push_client:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/client_deployment.yml
